# Data
data:
  root_dir: "./data/"

# Vector Database
vec_db:
  root_dir: "./chroma/"

# Embedding model
embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

# LLM
llm:
  model_name: "allenai/OLMo-2-0425-1B-Instruct"